# Generated by Django 6.0.4 on 2026-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
