# Generated by Django 6.0.4 on 2026-05-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_table_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table_no',
        ),
    ]
